###read all users (req ot protectyed rours)
GET http://localhost:4000/user-api/users  
Cookie:   token=yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZkBnbWFpbC5jb20iLCJpYXQiOjE3NzI5NDU3OTgsImV4cCI6MTc3Mjk0NTgwOH0.wpC1JzkC3mKUtPHuHeqpsQ85R8X5AtCDxRi_sXLpLzc; Path=/; HttpOnly; SameSite=Lax
### read a user by id 
GET http://localhost:4000/user-api/users
###
POST http://localhost:4000/user-api/users
Content-Type: application/json

{    
    "username":"vani",
    "password":"abc",
    "email":"vani@gmail.com",
    "age":25
}
    
###
PUT http://localhost:4000/user-api/users/69aa916501548bef914875a3
Content-Type: application/json


{
     
    "username":"nidhi",
    "password":"abc",
    "email":"abc@gmail.com",
    "age":20
     
}
###
DELETE http://localhost:4000/user-api/users/69aa916501548bef914875a3
###
GET http://localhost:4000/product-api/product
###
POST http://localhost:4000/product-api/product
Content-Type: application/json

{
    "productid":101,
    "productName":"mobile",
    "price":30000,
    "brand":"iphone"

}
###
POST http://localhost:4000/product-api/product
Content-Type: application/json

{
   "productid":102,
    "productName":"tV",
    "price":40000,
    "brand":"samsung"

}
###
POST http://localhost:2000/product-api/product
Content-Type: application/json

{
    "productid":103,
    "name":"footwear",
    "brand":"puma",
    "price":700

}
###
POST http://localhost:2000/product-api/product
Content-Type: application/json

{
    "productid":104,
    "name":"watch",
    "brand":"dressberry",
    "price":1500

}
###
POST http://localhost:2000/product-api/product
Content-Type: application/json

{
    "productid":105,
    "name":"bag",
    "brand":"zouk",
    "price":2000

}
###
GET http://localhost:4000/product-api/product/69aaa95d88490eb679b46bd6
###
PUT http://localhost:4000/product-api/product/69aace476469f256b5090065
Content-Type: application/json

{
    "productid":102,
    "productName":"tV",
    "price":20000,
    "brand":"samsung"

}
###
DELETE http://localhost:4000/product-api/product/69aaa9e2d667db9a60767479
### user login
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "email":"venu@gmail.com",
    "password":"abc"
}
### Add product to user cart
PUT http://localhost:4000/user-api/cart/product-id/69aaa95d88490eb679b46bd6
###
PUT http://localhost:4000/user-api/cart/product-id/69aaa95d88490eb679b46bd6